name: Build Tenderduty Binaries

on:
  release:
    types: [published]

env:
  GO_VERSION: "1.24"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          go build -ldflags "-s -w" -trimpath -o build/tenderduty-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Calculate sha256sum
        working-directory: ./build
        run: sha256sum tenderduty-${{ matrix.goos }}-${{ matrix.goarch }} > tenderduty-${{ matrix.goos }}-${{ matrix.goarch }}.sha256sum

      - name: Upload binaries
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*
