name: Docker

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - "**/caddy/**"
      - "**/docs/**"
      - "**.md"
      - ".github/**"

env:
  DOCKER_HUB_ORG: firstset
  DOCKER_HUB_REPO: tenderduty

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: |
            ${{ env.DOCKER_HUB_ORG }}/{{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.DOCKER_HUB_ORG }}/{{ env.DOCKER_HUB_REPO }}:${{ github.sha }}
            ${{ github.event.release.tag_name != '' && format('{0}/{1}:{2}', env.DOCKER_HUB_ORG, env.DOCKER_HUB_REPO, github.event.release.tag_name) || '' }}
